services:
  db:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - ./.env

  cache:
    image: redis:7.2.1-alpine
    volumes:
      - rediscache:/data
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

volumes:
  pgdata:
  rediscache:
