import type { Metadata } from "next";
import {
  Montserrat,
  Noto_Serif_Georgian,
  Open_Sans,
  Poetsen_One,
} from "next/font/google";

import "./globals.css";

import Providers from "@/shared/providers";

import { cn } from "@/lib/utils";
import { isDev } from "@/lib/utils/isType";

const fontSans = Open_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontSans1 = Montserrat({
  variable: "--font-sans1",
  subsets: ["latin"],
});

const fontSans2 = Poetsen_One({
  variable: "--font-sans2",
  subsets: ["latin"],
  weight: ["400"],
});

const fontSerif = Noto_Serif_Georgian({
  variable: "--font-serif",
  subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning={isDev()}
      className={cn(
        fontSans.variable,
        fontSans1.variable,
        fontSans2.variable,
        fontSerif.variable,
        "antialiased"
      )}
    >
      <body suppressHydrationWarning={isDev()}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
