declare module "@editorjs/embed";
declare module "@editorjs/link";
declare module "@editorjs/marker";
declare module "@editorjs/table";
declare module "@editorjs/underline";
declare module "@editorjs/paragraph";
declare module "@sotaproject/strikethrough";
declare module "editorjs-change-case";
declare module "@calumk/editorjs-codecup";
