import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";

import { ApolloWrapper } from "../components/wrappers/ApolloWrapper";
import RouteChangeProgress from "../components/wrappers/RouteChangeProgress";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-base-100")}>
        <ApolloWrapper>{children}</ApolloWrapper>
        <RouteChangeProgress />
        <div id="presentational" role="presentation" />
        <div id="tooltip" role="tooltip" aria-label="tooltip" />
      </body>
    </html>
  );
}
